webApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')  

webApp/surveys/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class SurveyForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    incentive = StringField('Incentive', validators=[DataRequired()])
    link =  StringField('Link', validators=[DataRequired()])
    assigned_to = TextAreaField('Assigned To', validators=[DataRequired()])
    submit = SubmitField('Create')

webApp/main/routes.py
from flask import render_template, request, Blueprint
from webApp.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route("/about") 
def about():
    return render_template('about.html', title='About') 

    

webApp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from webApp import db
from webApp.models import Post
from webApp.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required 
def new_post():
    form = PostForm() 
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post) 
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@login_required
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@login_required
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))
 

webApp/surveys/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from webApp import db
from webApp.models import Survey, User
from webApp.surveys.forms import SurveyForm

surveys = Blueprint('surveys', __name__)
 
@surveys.route("/survey/new/<users>", methods=['GET', 'POST'])
@login_required 
def new_survey(users):
    form = SurveyForm()
    if form.validate_on_submit():
        survey = Survey(title=form.title.data, description=form.description.data, incentive=form.incentive.data, link=form.link.data, assigned_to=form.assigned_to.data, author=current_user)
        db.session.add(survey) 
        db.session.commit()
        flash('Your Survey has been created!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        ids = ""
        emails = None
        import re
        import numpy
        pattern = re.compile(r"\'([^)]*)\'")
        emails = numpy.array(pattern.findall(users))
        nEmails = []
        for email in emails:
            nEmails += email.split(',')
        sEmails = []
        for email in nEmails:
            email = email.strip()
            email = email[1:len(email)-1]
            if('@' in email):
                sEmails.append(email)                    

        search = User.query.all()
        for user in search:
            if user.email in sEmails:
                ids += str(user.user_id) + ","

        form.assigned_to.data = ids

    return render_template('create_survey.html', title='New Survey', form=form, legend='New Survey')

@surveys.route("/survey/<int:survey_id>")
def survey(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    return render_template('survey.html', title=survey.title, survey=survey)


@login_required
@surveys.route("/survey/<int:survey_id>/update", methods=['GET', 'POST'])
def update_survey(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    if survey.author != current_user:
        abort(403)
    form = SurveyForm()
    if form.validate_on_submit():
        survey.title = form.title.data
        survey.description=form.description.data
        survey.incentive=form.incentive.data
        survey.link=form.link.data
        survey.assigned_to=form.assigned_to.data
        db.session.commit()
        flash('Your survey has been updated', 'success')
        return redirect(url_for('surveys.survey', survey_id=survey.id))
    elif request.method == 'GET':
        form.title.data = survey.title
        form.description.data = survey.description
        form.incentive.data = survey.incentive
        form.link.data = survey.link
        form.assigned_to.data = survey.assigned_to

    return render_template('create_survey.html', title='Update Survey', form=form, legend='Update Survey')

@login_required
@surveys.route("/survey/<int:survey_id>/delete", methods=['POST'])
def delete_survey(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    if survey.author != current_user:
        abort(403)
    db.session.delete(survey)
    db.session.commit()
    flash('Your survey has been deleted!', 'success')
    return redirect(url_for('main.home'))

webApp/users/routes.py
from wtforms.validators import NoneOf
from webApp.surveys.forms import SurveyForm
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from webApp import db, bcrypt
from webApp.models import Survey, User, Post
from webApp.users.forms import (RegistrationForm, CompanyRegistrationForm, LoginForm,
                                   RequestResetForm, ResetPasswordForm, FilterForm, SingleSearch, UpdateCompany, UpdateTeenager)
from webApp.users.utils import save_picture, send_reset_email
from datetime import datetime

users = Blueprint('users', __name__)
 
@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm() 
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(user_type='teenager', username=form.username.data, email=form.email.data, 
        password=hashed_password, first_name=form.first_name.data, last_name=form.last_name.data,
        age=form.age.data, city=form.city.data, state=form.state.data, birthday=form.birthday.data, 
        gender=form.gender.data, race=form.race.data, ethnicity=form.ethnicity.data, 
        religious_affiliation=form.religious_affiliation.data, political_affiliation=form.political_affiliation.data,
        social_class=form.social_class.data, sexuality=form.sexuality.data, hobbies=form.hobbies.data, 
        college_major=form.college_major.data, career_field=form.career_field.data, phone_number=form.phone_number.data, user_id=generate_id())
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

 
@users.route("/register/company", methods=['GET', 'POST'])
def register_company():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = CompanyRegistrationForm() 
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(user_type='company', username=form.username.data, email=form.email.data, password=hashed_password, 
        company_name=form.company_name.data, city=form.city.data, state=form.state.data, birthday=datetime.now(), user_id=generate_id())
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register_company.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login(): 
    #db.session.query(Model).delete()
    #db.session.commit()
    #db.drop_all()
    #db.create_all() 
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = None
    if current_user.user_type == "teenager":
        form = UpdateTeenager()
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = save_picture(form.picture.data)
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            #db.session.commit()
            current_user.age = form.age.data
            current_user.city = form.city.data
            current_user.state = form.state.data
            current_user.gender = form.gender.data
            current_user.religious_affiliation = form.religious_affiliation.data
            current_user.political_affiliation = form.political_affiliation.data
            current_user.social_class = form.social_class.data
            current_user.sexuality = form.sexuality.data
            current_user.hobbies = form.hobbies.data
            current_user.college_major = form.college_major.data
            current_user.career_field = form.career_field.data
            current_user.phone_number = form.phone_number.data
            db.session.commit()
            flash('Your account has been updated', 'success')
            return redirect(url_for('users.account'))

    elif current_user.user_type == "company":
        form = UpdateCompany()
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = save_picture(form.picture.data)
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.company_name = form.company_name.data
            current_user.city = form.city.data
            current_user.state = form.state.data
            db.session.commit()
            flash('Your account has been updated', 'success')
            return redirect(url_for('users.account'))

    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.city.data = current_user. city
        form.state.data = current_user.state
        if current_user.user_type == 'teenager':
            form.age.data = current_user.age
            form.gender.data = current_user.gender
            form.religious_affiliation.data = current_user.religious_affiliation
            form.political_affiliation.data = current_user.political_affiliation
            form.social_class.data = current_user.social_class
            form.sexuality.data = current_user.sexuality
            form.hobbies.data = current_user.hobbies
            form.college_major.data = current_user.college_major
            form.career_field.data = current_user.career_field
            form.phone_number.data = current_user.phone_number
        elif current_user.user_type == "company":
            form.company_name.data = current_user.company_name
    else:
        print (form.errors)      

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_post.html', posts=posts, user=user)


@users.route("/company/surveys/<string:username>")
def user_surveys(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    surveys = Survey.query.filter_by(author=user)\
        .order_by(Survey.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('company_surveys.html', surveys=surveys, user=user)


@users.route("/teenager/surveys/<string:username>")
def assigned_surveys(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    surveys = Survey.query.filter(Survey.assigned_to.contains(str(user.user_id)))\
        .order_by(Survey.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('teenager_surveys.html', surveys=surveys, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been send with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/filter", methods=['GET', 'POST'])
def filter():
    form = FilterForm() 
    if form.validate_on_submit():
        users = User.query.filter(User.user_type == 'teenager')
        #if form.first_name.data != None:
        #    users = User.query.filter(User.first_name.contains(str(form.first_name.data)))
        #if form.last_name.data != None:

webApp/templates/company_surveys.html
{% extends "layout.html" %}
{% block content %}
    {% for survey in surveys.items %}
        {%  if survey.author == current_user %}
            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + survey.author.image_file) }}"> 
                <div class="media-body">
                    <div class="article-metadata">
                        <small class="mr-2">{{ survey.author.username }}</small>
                        <small class="text-muted">{{ survey.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('surveys.survey', survey_id=survey.id) }}">{{ survey.title }}</a></h2>
                    <p class="article-content">{{ survey.link }}</p>
                </div> 
            </article>
        {% endif %}
    {% endfor %}
    {% for page_num in surveys.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if surveys.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}    
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

webApp/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"> 
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}    
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

webApp/templates/layout.html
<!DOCTYPE html> 
<html> 
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Lucy Tool - {{ title }}</title>
    {% else %}
        <title>Lucy Tool</title>
    {% endif %}</head>

    
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/"><img src="static/logo.png" width="30" height="auto" alt="logo" style="margin-right: 8px;"/>LucyTool</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                {% if current_user.user_type == "company" %}
                    <a class="nav-item nav-link" href="{{ url_for('users.user_surveys', username=current_user.username) }}">Your Surveys</a>
                {% elif current_user.user_type == "teenager" %}
                    <a class="nav-item nav-link" href="{{ url_for('users.assigned_surveys', username=current_user.username) }}">Assigned Surveys</a>
                {% endif %}  
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  {% if current_user.user_type == "company" %}
                    <a class="nav-item nav-link" href="{{ url_for('users.filter') }}">Filter Search</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.single_search') }}">Single Search</a>
                  {% endif %}  
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <div class="dropdown">
                    <button class="dropbtn" style="background-color: #ffffff00; padding: 8px 5px; color: #cbd5db;">Register</button>
                    <div class="dropdown-content">
                      <a class="nav-item nav-link" href="{{ url_for('users.register') }}" style="color: #3200a7">For Teenagers</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.register_company') }}" style="color: #3200a7">For Companies</a>
                    </div>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <!--
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
            -->
          </div>
        </div>
      </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

webApp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %} 
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info", style="color: White; border: 2px #3200a7;background-color: #3200a7") }}
                <small class="text-muted ml-2"> 
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

webApp/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"> 
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id)}}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

webApp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

webApp/templates/single_results.html
{% extends "layout.html" %}
{% block content %}
    <h2><a class="article-title"></a>Search Results</a></h2>
    {% if not user %}
        <article class="media content-section">
            <div class="media-body">
                <h2><a class="article-title"></a>No users found</a></h2>
            </div>
        </article>
    {% else %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}"> 
            <div class="media-body">
                <div class="article-metadata">
                    <small class="mr-2">{{ user.username }}</small>
                </div>
                <h2><a class="article-title"></a>{{ user.first_name }}</a></h2>
                <h2><a class="article-title"></a>{{ user.last_name }}</a></h2>
                <h2><a class="article-title"></a>{{ user.phone_number }}</a></h2>
                <h2><a class="article-title"></a>{{ user.email }}</a></h2>
            </div>
        </article>
    {% endif %}
{% endblock content %}